/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-05-31 15:25:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.decorators;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.2.jar", Long.valueOf(1620615706071L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1621779687531L));
    _jspx_dependants.put("/common/user/header1.jsp", Long.valueOf(1622459892080L));
    _jspx_dependants.put("jar:file:/D:/Project/WebsiteBanMyPham/Server/wtpwebapps/MyPhamSpring/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("jar:file:/D:/Project/WebsiteBanMyPham/Server/wtpwebapps/MyPhamSpring/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.2.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1620615707245L));
    _jspx_dependants.put("/common/user/footer.jsp", Long.valueOf(1622215250598L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdecorator_005fbody_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdecorator_005fbody_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fdecorator_005fbody_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Newsreader&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<!-- CSS Libraries -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/slick/slick.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/slick/slick-theme.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header_tv>\r\n");
      out.write("<div class=\"bottom-bar mb-0\" style=\"z-index: 3;\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row align-items-center\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/mypham/trangchu\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\"\r\n");
      out.write("\t\t\t\t\t\talt=\"Logo\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t\t\t<form action=\"product\">\r\n");
      out.write("\t\t\t\t\t\t<input name=\"tenSP\" type=\"text\" placeholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<div class=\"user\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/wish\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn wishlist\"> <i class=\"fa fa-heart\"></i> <span>(0)</span>\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cart/\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn cart\"> <i class=\"fa fa-shopping-cart\"></i> <span>(0)</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg bg-pri\"\r\n");
      out.write("\tstyle=\"z-index: 3; height: 38px;\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-bs-target=\"#main_nav\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse position-relative\" id=\"main_nav\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown hover-parent\" style=\"z-index: 3;\">\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle text-white font-weight-bold text-uppercase pl-3\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" data-bs-toggle=\"dropdown\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-bars text-white\"></i> <span class=\"text-white\">&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\tDanh mục sản phẩm </span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu mt-0 rounded-1 py-0\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"margin-left: 37px;\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"has-megasubmenu\"><a style=\"z-index: 3;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hover-overlay dropdown-item text-capitalize\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\"> <span>Chăm sóc da mặt</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"float-right\"><em class=\"fa fa-angle-right\"> </em></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"megasubmenu dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Nổi bật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Bán chạy</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Hàng mới</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Khuyến mãi</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tđiểm</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmặt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt môi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Thực\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphẩm chức năng</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Chống lão\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thõa</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Bổ sung\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcollagen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc cơ thể</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Làm sạch cơ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng thể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Kem massage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy lông</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc da mặt</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Quy trình\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tchăm sóc da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Vấn đề về\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tda</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Loại da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu gội</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu xả</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng tóc</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Nước\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thoa sóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa tự\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnhiên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttổng hợp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tquyến rũ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.sapo.vn/blog/wp-content/uploads/2016/01/FreeGreatPicture.com-4540-hd-cosmetics-ads-wallpaper.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\theight=\"200px\" width=\"100%\" alt=\"QC TV\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: middle; border-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"has-megasubmenu\"><a style=\"z-index: 3;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hover-overlay dropdown-item text-capitalize\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\"> <span>Chăm sóc cơ thể</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"float-right\"><em class=\"fa fa-angle-right\"> </em></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"megasubmenu dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Nổi bật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Bán chạy</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Hàng mới</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Khuyến mãi</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tđiểm</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmặt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt môi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Thực\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphẩm chức năng</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Chống lão\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thõa</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Bổ sung\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcollagen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc cơ thể</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Làm sạch cơ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng thể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Kem massage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy lông</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc da mặt</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Quy trình\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tchăm sóc da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Vấn đề về\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tda</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Loại da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu gội</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu xả</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng tóc</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Nước\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thoa sóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa tự\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnhiên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttổng hợp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tquyến rũ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.sapo.vn/blog/wp-content/uploads/2016/01/FreeGreatPicture.com-4540-hd-cosmetics-ads-wallpaper.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\theight=\"200px\" width=\"100%\" alt=\"QC TV\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: middle; border-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"has-megasubmenu\"><a style=\"z-index: 3;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hover-overlay dropdown-item text-capitalize\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\"> <span>Chăm sóc tóc</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"float-right\"><em class=\"fa fa-angle-right\"> </em></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"megasubmenu dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Nổi bật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Bán chạy</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Hàng mới</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Khuyến mãi</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tđiểm</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmặt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt môi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Thực\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphẩm chức năng</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Chống lão\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thõa</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Bổ sung\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcollagen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc cơ thể</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Làm sạch cơ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng thể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Kem massage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy lông</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc da mặt</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Quy trình\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tchăm sóc da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Vấn đề về\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tda</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Loại da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu gội</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu xả</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng tóc</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Nước\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thoa sóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa tự\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnhiên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttổng hợp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tquyến rũ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.sapo.vn/blog/wp-content/uploads/2016/01/FreeGreatPicture.com-4540-hd-cosmetics-ads-wallpaper.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\theight=\"200px\" width=\"100%\" alt=\"QC TV\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: middle; border-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"has-megasubmenu\"><a style=\"z-index: 3;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hover-overlay dropdown-item text-capitalize\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\"> <span>Nước hoa</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"float-right\"><em class=\"fa fa-angle-right\"> </em></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"megasubmenu dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Nổi bật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Bán chạy</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Hàng mới</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Khuyến mãi</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tđiểm</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmặt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt môi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Thực\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphẩm chức năng</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Chống lão\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thõa</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Bổ sung\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcollagen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc cơ thể</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Làm sạch cơ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng thể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Kem massage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy lông</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc da mặt</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Quy trình\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tchăm sóc da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Vấn đề về\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tda</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Loại da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu gội</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu xả</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng tóc</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Nước\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thoa sóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa tự\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnhiên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttổng hợp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tquyến rũ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.sapo.vn/blog/wp-content/uploads/2016/01/FreeGreatPicture.com-4540-hd-cosmetics-ads-wallpaper.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\theight=\"200px\" width=\"100%\" alt=\"QC TV\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: middle; border-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"has-megasubmenu\"><a style=\"z-index: 3;\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"hover-overlay dropdown-item text-capitalize\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\"> <span>Trang điểm</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"float-right\"><em class=\"fa fa-angle-right\"> </em></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"megasubmenu dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-12 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Nổi bật</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Bán chạy</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Hàng mới</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn mw-btn-135 ml-3 rounded-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"product\">Khuyến mãi</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tđiểm</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmặt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmôi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Trang điểm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=5\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy trang\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmắt môi</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Thực\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tphẩm chức năng</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Chống lão\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thõa</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Bổ sung\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcollagen</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=6\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc cơ thể</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Làm sạch cơ\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tthể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng thể</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Kem massage</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Tẩy lông</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc da mặt</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Quy trình\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tchăm sóc da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Vấn đề về\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tda</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Loại da</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Chăm\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu gội</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dầu xả</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Dưỡng tóc</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"title font-weight-bold text-uppercase pl-3\">Nước\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thoa sóc tóc</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled pl-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa tự\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tnhiên</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttổng hợp</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"product?maDanhMuc=4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"text-capitalize text-decoration-none\">Nước hoa\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tquyến rũ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"https://www.sapo.vn/blog/wp-content/uploads/2016/01/FreeGreatPicture.com-4540-hd-cosmetics-ads-wallpaper.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\theight=\"200px\" width=\"100%\" alt=\"QC TV\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"vertical-align: middle; border-style: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link text-uppercase text-white\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product\">Danh sách sản\r\n");
      out.write("\t\t\t\t\t\tphẩm</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link text-uppercase text-white\"\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/checkout\">Check out</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link text-uppercase text-white\" href=\"account\">Tài\r\n");
      out.write("\t\t\t\t\t\tkhoản</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle text-white text-uppercase\"\r\n");
      out.write("\t\t\t\t\thref=\"javascript:void(0)\" data-bs-toggle=\"dropdown\"> More pages\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("\t\t\t\t\t\t<li style=\"margin-top: -8px;\"><a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/wish\"> Wishlist</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"margin-bottom: -8px;\"><a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\"> Contact Us\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</header_tv>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_decorator_005fbody_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"back-to-top\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-widget\">\r\n");
      out.write("\t\t\t\t\t<h2>Thông tin liên hệ</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-info\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-map-marker\"></i>103 Phú Định, Phường 16, Quận 8, TP. HCM\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>estore@gmail.com\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i>+123-456-7890\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-widget\">\r\n");
      out.write("\t\t\t\t\t<h2>Theo dõi chúng tôi</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"contact-info\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\"><i class=\"fab fa-twitter\"></i></a> <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-facebook-f\"></i></a> <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-linkedin-in\"></i></a> <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-instagram\"></i></a> <a href=\"\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fab fa-youtube\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-widget\">\r\n");
      out.write("\t\t\t\t\t<h2>Thông tin</h2>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Về Estore</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Điều khoản</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-widget\">\r\n");
      out.write("\t\t\t\t\t<h2>Thông tin mua hàng</h2>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Chính sách thanh toán</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Chính sách giao hàng</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Chính sách khác</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row payment align-items-center\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"payment-method\">\r\n");
      out.write("\t\t\t\t\t<h2>Chấp nhật thanh toán:</h2>\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/payment-method.png\" alt=\"Payment Method\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"payment-security\">\r\n");
      out.write("\t\t\t\t\t<h2>Đơn vị bảo mật:</h2>\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/godaddy.svg\" alt=\"Payment Security\" /> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/norton.svg\" alt=\"Payment Security\" /> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/ssl.svg\" alt=\"Payment Security\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer Bottom Start -->\r\n");
      out.write("<div class=\"footer-bottom\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6 copyright\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tCopyright &copy; <a href=\"https://htmlcodex.com\">EStore</a>.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-6 template-by\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\tDesign By <a href=\"#\">Nhóm 29</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"#\" class=\"back-to-top\"><i class=\"fa fa-chevron-up\"></i></a>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScript Libraries -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/easing/easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/slick/slick.min.js\"></script>\r\n");
      out.write("\t<!-- Template Javascript -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/main1.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /common/taglib.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/user");
      // /common/taglib.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("url");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /common/taglib.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("resources/user/img");
      // /common/taglib.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("urlUserImg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /common/taglib.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("resources/user/upload");
      // /common/taglib.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setVar("urlUpload");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /decorators/user.jsp(28,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/user/css/style.css");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /common/user/header1.jsp(697,34) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle text-white\"\r\n");
          out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\" data-bs-toggle=\"dropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </a>\r\n");
          out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
          out.write("\t\t\t\t\t\t\t<li style=\"margin-top: -8px;\"><a class=\"dropdown-item\"\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/account\">Account</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li style=\"margin-bottom: -8px;\"><a class=\"dropdown-item\"\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">Logout</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /common/user/header1.jsp(708,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle text-white\"\r\n");
          out.write("\t\t\t\t\t\t\thref=\"javascript:void(0)\" data-bs-toggle=\"dropdown\"> <i\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"fas fa-user\"></i>\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
          out.write("\t\t\t\t\t\t\t<li style=\"margin-top: -8px;\"><a class=\"dropdown-item\"\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">Login</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t<li style=\"margin-bottom: -8px;\"><a class=\"dropdown-item\"\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">Register</a></li>\r\n");
          out.write("\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_decorator_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  decorator:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_decorator_005fbody_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fdecorator_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    boolean _jspx_th_decorator_005fbody_005f0_reused = false;
    try {
      _jspx_th_decorator_005fbody_005f0.setPageContext(_jspx_page_context);
      _jspx_th_decorator_005fbody_005f0.setParent(null);
      int _jspx_eval_decorator_005fbody_005f0 = _jspx_th_decorator_005fbody_005f0.doStartTag();
      if (_jspx_th_decorator_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdecorator_005fbody_005fnobody.reuse(_jspx_th_decorator_005fbody_005f0);
      _jspx_th_decorator_005fbody_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_decorator_005fbody_005f0, _jsp_getInstanceManager(), _jspx_th_decorator_005fbody_005f0_reused);
    }
    return false;
  }
}
